apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- statefulset.yaml
- service.yaml

commonLabels:
  app: fou
  tier: db
  component: user-sql

generatorOptions:
  disableNameSuffixHash: true


secretGenerator:
- name: user-sql
  files:
  - sa-password
  type: Opaque

namespace: fou
