apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- secret.yaml
- service.yaml
- namespace.yaml

commonLabels:
  app: fou
  tier: backend
  component: user

namespace: fou